
services:
  db:
    build: .
    container_name: sql_medico
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: Sistema_Medico
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    ports:
      - "3306:3306"
    volumes:
      # Persistencia de datos (base de datos)
      - ./volumes/sql/sqlData:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: unless-stopped
